#! /bin/sh

#feh --bg-center ~/.wallpapers/palm-wallpaper.jpg

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2 
bspc config window_gap          8
bspc config top_padding         0
bspc config bottom_padding      0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# AUTOSTART
$HOME/.config/polybar/launch.sh

