#! /usr/bin/zsh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor eDP -d web1 code1 term1 image1 music1 mail1
bspc monitor HDMI-A-0 -d web2 code2 term2 image2 mail2

bspc config border_width        0 
bspc config window_gap          16
bspc config top_padding         0
bspc config bottom_padding      0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# AUTOSTART
startup
